### ISSUE TITLE
install failed Sparse transformer library

### ISSUE THREAD

**Issue by jinxxo-j** [raktimgg/FlashMix#2]
Hello!

I have another problem for setting conda environment,
error messages are below

(flashmix) jinwoo@mutalisk12:~/FlashMix/src/models/SphereFormer/SparseTransformer$ pip install .
Processing /home/jinwoo/FlashMix/src/models/SphereFormer/SparseTransformer
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: sptr
  Building wheel for sptr (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [48 lines of output]
      running bdist_wheel
      running build
      running build_ext
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/home/jinwoo/FlashMix/src/models/SphereFormer/SparseTransformer/setup.py", line 12, in <module>
          setup(
        File "/home/jinwoo/anaconda3/envs/flashmix/lib/python3.10/site-packages/setuptools/__init__.py", line 117, in setup
          return distutils.core.setup(**attrs)
        File "/home/jinwoo/anaconda3/envs/flashmix/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 183, in setup
          return run_commands(dist)
        File "/home/jinwoo/anaconda3/envs/flashmix/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 199, in run_commands
          dist.run_commands()
        File "/home/jinwoo/anaconda3/envs/flashmix/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 954, in run_commands
          self.run_command(cmd)
        File "/home/jinwoo/anaconda3/envs/flashmix/lib/python3.10/site-packages/setuptools/dist.py", line 950, in run_command
          super().run_command(command)
        File "/home/jinwoo/anaconda3/envs/flashmix/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 973, in run_command
          cmd_obj.run()
        File "/home/jinwoo/anaconda3/envs/flashmix/lib/python3.10/site-packages/setuptools/command/bdist_wheel.py", line 398, in run
          self.run_command("build")
        File "/home/jinwoo/anaconda3/envs/flashmix/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
          self.distribution.run_command(command)
        File "/home/jinwoo/anaconda3/envs/flashmix/lib/python3.10/site-packages/setuptools/dist.py", line 950, in run_command
          super().run_command(command)
        File "/home/jinwoo/anaconda3/envs/flashmix/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 973, in run_command
          cmd_obj.run()
        File "/home/jinwoo/anaconda3/envs/flashmix/lib/python3.10/site-packages/setuptools/_distutils/command/build.py", line 135, in run
          self.run_command(cmd_name)
        File "/home/jinwoo/anaconda3/envs/flashmix/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
          self.distribution.run_command(command)
        File "/home/jinwoo/anaconda3/envs/flashmix/lib/python3.10/site-packages/setuptools/dist.py", line 950, in run_command
          super().run_command(command)
        File "/home/jinwoo/anaconda3/envs/flashmix/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 973, in run_command
          cmd_obj.run()
        File "/home/jinwoo/anaconda3/envs/flashmix/lib/python3.10/site-packages/setuptools/command/build_ext.py", line 98, in run
          _build_ext.run(self)
        File "/home/jinwoo/anaconda3/envs/flashmix/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 359, in run
          self.build_extensions()
        File "/home/jinwoo/anaconda3/envs/flashmix/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 518, in build_extensions
          _check_cuda_version(compiler_name, compiler_version)
        File "/home/jinwoo/anaconda3/envs/flashmix/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 413, in _check_cuda_version
          raise RuntimeError(CUDA_MISMATCH_MESSAGE.format(cuda_str_version, torch.version.cuda))
      RuntimeError:
      The detected CUDA version (11.6) mismatches the version that was used to compile
      PyTorch (12.1). Please make sure to use the same CUDA versions.

**Comment by raktimgg** [comment]
Hi, it seems like the issue stems from a mismatch between your PyTorch installation and the version of CUDA available on your system. You're currently using CUDA 11.6, but your PyTorch was installed with support for CUDA 12.1, which is causing the installation errors for the Sparse Transformer library.

To resolve this, you'll need to align the PyTorch and CUDA versions by installing PyTorch with CUDA 11.6 (or a compatible version). Here's can use the following commands to create the environment with CUDA 11.6 support:
 
conda create --name flashmix python=3.10.11
conda activate flashmix
pip install numpy pyyaml opencv-python matplotlib
pip install torch --index-url https://download.pytorch.org/whl/cu117
pip install torch-scatter -f https://data.pyg.org/whl/torch-2.0.1+cu117.html
pip install torch-sparse -f https://data.pyg.org/whl/torch-2.0.1+cu117.html
pip install torch-cluster -f https://data.pyg.org/whl/torch-2.0.1+cu117.html

In requirements.txt, change spconv-cu120 to spconv-cu117 and cumm-cu120 to cumm-cu117

pip install -r requirements.txt

After completing these steps, you should be able to successfully build the Sparse Transformer library from source. Let me know if you encounter any further issues!
