### ISSUE TITLE
Some question

### ISSUE THREAD

**Issue by Wansit99** [raktimgg/FlashMix#3]
Thank you for your excellent work. How do you achieve the visualization in Figure 3a? it looks very cool

**Comment by Wansit99** [comment]
Hello!

I have another problem for training,
error messages are below

python src/main.py --dataset vReLoc                                                                                                                     11s Py frnet11.3 wangsiyuan@ESC8000-G4
/home/wangsiyuan/miniconda3/envs/frnet11.3/lib/python3.8/site-packages/timm/models/layers/__init__.py:48: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
{'exp_num': 1, 'do_wandb': False, 'do_validation': False, 'base_ds': '/home/wangsiyuan/FlashMix-main/data/vReLoc/', 'pickle_loc': 'src/utils/vReLoc_0.pkl', 'val_pickle_loc': 'src/utils/vReLoc_0.pkl', 'feat_extractor_model_path': 'src/checkpoints/SALSA/Model/feat_extractor.pth', 'regressor': {'num_mixer_channels': 1, 'pose_regressor_layers': 6, 'global_desc_dim_scale': 2}, 'num_clusters': 50, 'loss': {'contrastive_loss_name': 'triplet_loss', 'pose_loss_rot_weight': 20, 'contrastive_loss_scale': 1}, 'training': {'batch_size': 1280, 'epochs': 75, 'max_lr': 0.001, 'pct_start': 0.01, 'final_div_factor': 100, 'save_folder': 'src/checkpoints/FlashMix'}}
Experiment instance  1
Initializing models
Creating Training Feature Buffer
  0%|                                                                                                                                                                                      | 0/7 [00:05<?, ?it/s]
Traceback (most recent call last):
  File "src/main.py", line 57, in <module>
    main()
  File "src/main.py", line 49, in main
    vreloc_main(config)
  File "/home/wangsiyuan/FlashMix-main/src/train_vReLoc.py", line 123, in main
    local_features = feature_model(coord, xyz, feat, batch_number)
  File "/home/wangsiyuan/miniconda3/envs/frnet11.3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/wangsiyuan/FlashMix-main/src/models/model_zoo.py", line 57, in forward
    local_features = self.feature_encoder(sinput, xyz, batch)
  File "/home/wangsiyuan/miniconda3/envs/frnet11.3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/wangsiyuan/FlashMix-main/src/models/SphereFormer/model/unet_spherical_transformer.py", line 292, in forward
    output, output_list = self.unet(output, xyz, batch)
  File "/home/wangsiyuan/miniconda3/envs/frnet11.3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/wangsiyuan/FlashMix-main/src/models/SphereFormer/model/unet_spherical_transformer.py", line 188, in forward
    transformer_features = self.transformer_block(output.features, xyz, batch)
  File "/home/wangsiyuan/miniconda3/envs/frnet11.3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/wangsiyuan/FlashMix-main/src/models/SphereFormer/model/spherical_transformer.py", line 326, in forward
    sptr_tensor = self.attn(sptr_tensor)
  File "/home/wangsiyuan/miniconda3/envs/frnet11.3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/wangsiyuan/FlashMix-main/src/models/SphereFormer/model/spherical_transformer.py", line 171, in forward
    index_0, index_0_offsets, n_max, index_1, index_1_offsets, sort_idx = get_indices_params(
  File "/home/wangsiyuan/FlashMix-main/src/models/SphereFormer/SparseTransformer/sptr/utils.py", line 59, in get_indices_params
    v2p_map, k, counts = grid_sample(xyz, batch, window_size, start=None, return_p2v=False, return_counts=True)
  File "/home/wangsiyuan/FlashMix-main/src/models/SphereFormer/SparseTransformer/sptr/utils.py", line 26, in grid_sample
    cluster = voxel_grid(pos, batch, size, start=start) #[N, ]
  File "/home/wangsiyuan/miniconda3/envs/frnet11.3/lib/python3.8/site-packages/torch_geometric/nn/pool/voxel_grid.py", line 52, in voxel_grid
    pos = torch.cat([pos, batch.view(-1, 1).to(pos.dtype)], dim=-1)
RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 113960 but got size 3 for tensor number 1 in the list.

**Comment by Wansit99** [comment]
And when I test the model, using src/utils/create_vreloc_pickle.py to generate pickle for vreloc, It only has vReLoc_0.pkl, but no vReLoc_10_test1.pkl in the folder to test, also I don't know how to use the trained model you provided, Thanks for your work

**Comment by raktimgg** [comment]
RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 113960 but got size 3 for tensor number 1 in the list.

Could you share the shapes of the following inputs to the feature_model in line 123 of src/train_vReLoc.py?
* coord
* xyz
* feat
* batch_number
This will help diagnose the mismatch issue.


Regarding the next issue, the vReLoc_10_test1.pkl file is optional and only used for validation. By default, the do_validation argument is set to False, so the vReLoc_10_test1.pkl file is not required.
However, if you need to create it, you can generate it similarly to the training .pkl file using:
cd src/utils/
python create_vreloc_pickle.py --data_dir <path_to_Oxford-Radar> --save_dir <path_to_save_pickle> --d_thresh 10
To specify which sequences to use for validation, edit test_sequences in line 72 of src/utils/create_vreloc_pickle.py.

**Comment by jinxxo-j** [comment]
> RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 113960 but got size 3 for tensor number 1 in the list.
> 
> Could you share the shapes of the following inputs to the feature_model in line 123 of src/train_vReLoc.py?
> 
> * coord
> * xyz
> * feat
> * batch_number
>   This will help diagnose the mismatch issue.
> 
> Regarding the next issue, the vReLoc_10_test1.pkl file is optional and only used for validation. By default, the do_validation argument is set to False, so the vReLoc_10_test1.pkl file is not required. However, if you need to create it, you can generate it similarly to the training .pkl file using: cd src/utils/ python create_vreloc_pickle.py --data_dir <path_to_Oxford-Radar> --save_dir <path_to_save_pickle> --d_thresh 10 To specify which sequences to use for validation, edit test_sequences in line 72 of src/utils/create_vreloc_pickle.py.

Hello! I have the same issue!  
: > RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 113960 but got size 3 for tensor number 1 in the list.  
coord.shape : torch.Size([115132, 3])
xyz.shape : torch.Size([115132, 3])
feat.shape : torch.Size([115132, 3])
batch_number.shape : torch.Size([115132])

**Comment by raktimgg** [comment]
Hi,  

It looks like there's an issue with the **SparseTransformer** library. To resolve it, navigate to:  

**`<path-to-SparseTransformer>/sptr/utils.py`**  

On **line 25**, modify the following line:  

```python
cluster = voxel_grid(pos, batch, size, start=start)
```
Change it to:

```python
cluster = voxel_grid(pos=pos, batch=batch, size=size, start=start)
```

This explicitly assigns each argument, which should fix the issue. Let me know if you encounter any other problems!
